### ISSUE TITLE
Need permissions to create repos in SpatioTemporal group to transfer sidecar creation repo

### ISSUE THREAD

**Issue by captainkirk99** [SpatioTemporal/STARE#46]
We talked about transferring the repo containing the sidecar creation code for MODIS files to your GitHub group, SpatioTemporal.

To do that, I need permissions to create repos in that group. Then I can transfer the repo.

**Comment by michaelleerilee** [comment]
Is that admin privileges?

**Comment by michaelleerilee** [comment]
Okay, looks like admin is for the repo, not the group. I've invited you to the group.
