### ISSUE TITLE
is there a canonical paper describing STARE that I can reference in STAREmaster docs?

### ISSUE THREAD

**Issue by captainkirk99** [SpatioTemporal/STARE#59]
I keep forgetting to ask in our meetings...

Is there some paper or papers that describe STARE which I can reference in my STAREmaster documentation?

**Comment by michaelleerilee** [comment]
[STARE Towards Unprecedented Geo-Data Interoperability](https://www.researchgate.net/publication/320908197_STARE_-_TOWARD_UNPRECEDENTED_GEO-DATA_INTEROPERABILITY)

A better paper will be published later this year.

**Comment by captainkirk99** [comment]
I also found another one on ResearchNet that seemed relevant so I cite that too. The README will contain:

```
Kuo, K-S and ML Rilee, “STARE – Toward unprecedented geo-data
interoperability,” 2017 Conference on Big Data from Space. Toulouse,
France. 28-30 November 2017, retrieved on Sep 19,2020 from
https://www.researchgate.net/publication/320908197_STARE_-_TOWARD_UNPRECEDENTED_GEO-DATA_INTEROPERABILITY.

Kuo, K-S, H. YuYu, and ML Rilee, "Leveraging STARE for Co-aligned Data
Locality with netCDF and Python MPI", 2019 IEEE International
Geoscience and Remote Sensing Symposium, June 2019, retrieved on Sep
19, 2020 from
https://www.researchgate.net/publication/337504144_Leveraging_STARE_for_Co-aligned_Data_Locality_with_netCDF_and_Python_MPI.

```

In the references section. I will close this issue. Thanks!
